### PR TITLE
Fix dnd style

### LINKED ISSUE #92: Small resize on DnD
When dragging rules, the drag space underneath shrinks a few pixels, then when dropping it gains those pixels bank. To fix this visual tick, we should make sure the spacing of the hover container is the same height so that the parent container height doesn't change when moving things around.

### PR DESCRIPTION
**Pull request by ycleptkellan**
resolves #92, breaks out helper methods and adds tests. 

http://gph.is/2zhlhL9

### CODE REVIEW

File: src/components/actions/Reply/ReplyForm.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default class ReplyForm extends React.Component<ReplyFormProps> {
     public onValid(widgets: { [name: string]: any }): void {
         const localizedObject = this.props.getLocalizedObject();
 
-        const textarea = widgets['Message'] as TextInputElement;
+        const textarea = widgets.Message as TextInputElement;
```
Comment (ericnewcomer) [inline src/components/actions/Reply/ReplyForm.tsx]: this feels weird, would much rather they not be accessed with dot notation since they are keyed by name which has case and spaces, etc.

Comment (ycleptkellan) [reply src/components/actions/Reply/ReplyForm.tsx]: OK tslint was yelling at me over that: https://palantir.github.io/tslint/rules/no-string-literal/

Case does make it awkward, happy to turn off that rule & revert.

Comment (ericnewcomer) [reply src/components/actions/Reply/ReplyForm.tsx]: I want my cake too though. No argument, I definitely don't like implicit any on normal object properties, but don't want to have that as an issue for dictionary lookups. The explicit cast here I thought should address this though.

**Comment by ycleptkellan** [comment]
I haven't been able to replicate that for some reason, can I have a repro case to try?

File: src/components/actions/Reply/ReplyForm.tsx (hunk 1 above)
Comment (ycleptkellan) [reply src/components/actions/Reply/ReplyForm.tsx]: Gotcha, I agree but it looks like they're just checking the lookup string: 

https://github.com/palantir/tslint/blob/4c29dd9fd14afda79ab8e2b2fc10a868adbc9e44/src/rules/noStringLiteralRule.ts#L54 

That might be why it yells even with the type cast.
