### PR TITLE
Fix breaking out like-named routes

### LINKED ISSUE #847: Renaming repeated categories creates exits with duplicate UUIDs
https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/conversation/26207653563

Looks like you can recreate this on any ruleset where categories repeat, and then you try to change one of the repeated categories. For example given

Captura de Pantalla 2020-03-18 a la(s) 09 20 15

I can't change _Others_ unless I change both of them. Otherwise get validation failed dialog, and POST shows flow has duplicate exit UUIDs for this router.

### PR DESCRIPTION
**Pull request by ericnewcomer**
Fixes #847

### CODE REVIEW

File: src/testUtils/matchers.ts [hunk 1]
```diff
@@ -11,6 +11,27 @@ interface MatchResult {
...
+    } else {
+      seen[stringified] = true;
+    }
+  }
+
+  return {
+    message: () => 'Array is unique',
+    pass: true
+  };
+}
```
Comment (ericnewcomer) [inline src/testUtils/matchers.ts]: Handy new jest matcher checking that the stringified value of each object in an array is unique
